version: '3'
services: 
  mongodb:
    image: 'mongo:latest'
  redis:
    image: 'redis:latest'
  postgres:
    image: 'postgres:latest'
    env_file: ./env/postgres.env
  nginx:
    restart: always
    build:
      context: ./00-nginx
    # image: eliudarudo/complex-voting-app-nginx
    ports:
      - '80:80'
  worker:
    build:
      context: ./06-worker
    # image: eliudarudo/complex-voting-app-worker
    env_file: ./env/worker.env
    volumes:
      - /app/node_modules
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGO_URI=mongodb
      - MONGO_PORT=27017
      - PGHOST=postgres
      - PGPORT=5432
    depends_on:   
      - postgres
      - redis 
  manager:
    build:
      context: ./05-manager
    # image: eliudarudo/complex-voting-app-manager
    env_file: ./env/manager.env
    volumes:
      - /app/node_modules  
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - WSSERVER=wsserver
    depends_on: 
      - redis 
  wsserver:
    build:
      context: ./04-ws-server
    # image: eliudarudo/complex-voting-app-ws-server
    volumes:
      - /app/node_modules   
    environment:
      - MANAGER=manager  
  admin:
    build:
      context: ./02-admin
    # image: eliudarudo/complex-voting-app-admin
    volumes:
      - /app/node_modules      
  voter:
    build:
      context: ./01-voter
    # image: eliudarudo/complex-voting-app-voter
    volumes:
      - /app/node_modules     
  results:
    build:
      context: ./03-results
    # image: eliudarudo/complex-voting-app-results
    volumes:
      - /app/node_modules