version: '3'
services: 
  mongodb:
    image: 'mongo:latest'
  redis:
    image: 'redis:latest'
  postgres:
    image: 'postgres:latest'
  nginx:
    restart: always
    build:
      context: ./00-nginx
    ports:
      - '80:80'
  worker:
    build:
      context: ./06-worker
    volumes:
      - /app/node_modules
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGO_URI=mongodb
      - MONGO_PORT=27017
      - MONGO_DB=voter_data
      - PGHOST=postgres
      - PGUSER=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
    depends_on:   
      - postgres
      - redis 
  manager:
    build:
      context: ./05-manager
    volumes:
      - /app/node_modules  
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - WSSERVER=wsserver
      - ADMIN_EMAIL=admin@test.com
      - ADMIN_PASSWORD=admin_test
      - JWT_EXPIRATION=604800
      - JWT_SECRET=jwt_guy
      - VOTING_ACTIVE=true
    depends_on: 
      - redis 
  wsserver:
    build:
      context: ./04-ws-server
    volumes:
      - /app/node_modules   
    environment:
      - MANAGER=manager  
  admin:
    build:
      context: ./02-admin
    volumes:
      - /app/node_modules      
  voter:
    build:
      context: ./01-voter
    volumes:
      - /app/node_modules     
  results:
    build:
      context: ./03-results
    volumes:
      - /app/node_modules